### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by coderPB** [datawrapper/datawrapper#200]
After installing datawrapper and its plugins, when trying to create a new chart get the error below
![untitled](https://cloud.githubusercontent.com/assets/19436255/15371537/4c9a8e1e-1d12-11e6-8d71-2271b3096ac1.png)
I saw no problem with the autoload.php forum. can anybody help me?

I'm using WAMP on Windows 10 64bits, with php 5.5.12, MySQL 5.6.17 and apache 2.4.9.

**Comment by trond7** [comment]
I got the same problem on a fresh install on LAMP 

**Git clone date**: 2016.05.19 
**datawrapper version**: (version 1.9.3 (master))
**Environment**:  x86_64, ubuntu 14.04 LTS with Apache/2.4.7, PHP 5.5.9 MYSQL 5.5.49

Welcome screen, signup and log in, profile editing works fine.
First step (New chart) gives the identical error message as previous comment. 

**My bugtracking so far:**
- Both domains for datawrapper app and static chart seems to respond fine
- Tried to copy dw.js/dw-2.0.js to dw.js/dw-2.0.min.js and www/static/js/dw-2.0.min.js

- Trace #3 says something about write permission.
I have checked all the permission in the install guide:
https://github.com/datawrapper/datawrapper/wiki/Installing-Datawrapper#basic-setup

I have one issue with the last permission in the guide because i cant find the last path:
vendor/htmlpurifier/standalone/HTMLPurifier/DefinitionCache/Serializer
But i do find the directory Serializer in:
../datawrapper/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer

I gave the directory above and all the other path mentioned in setup instructions to chmod 777

**Comment by deshetti** [comment]
@trond7 check giving access to the following directory: datawrapper/tmp

**Comment by mbejdk** [comment]
/datawrapper/lib/utils/parse_vis_options.php throws the same error on my installation:

Code: 2
Message: Invalid argument supplied for foreach()

Is it check_chart_writable() which is failing?

**Comment by lorenries** [comment]
@mbjedk did you figure out what was causing the slim application error on /datawrapper/lib/utils/parse_vis_options.php?

I'm getting the same error, but interestingly only on line chart creation (other chart types seem to be working fine).

**Comment by mbjedk** [comment]
@lorenries : No. I do not get to the Visualize step.

I still get the error after proceeding from step 2:
![skaermbillede 2017-01-25 kl 10 54 22](https://cloud.githubusercontent.com/assets/1516691/22285617/ac7345ec-e2ec-11e6-9de3-0a9d8260ebaa.png)

The parse_vis_options is basically doing some for loops, so I guess the data passed is corrupt somehow.

**Comment by gka** [comment]
I'm sorry but we can't provide support for installing Datawrapper, other than this document
https://github.com/datawrapper/datawrapper/wiki/Installing%20Datawrapper

if you get Datawrapper to work on your system, please update (add it to) our [installation guide](https://github.com/datawrapper/datawrapper/wiki/Installing%20Datawrapper) to share with other users.
